---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

notify:
  - if: 'build.branch =~ /^((main)|([0-9]+\.[0-9]+))\$/ && (build.state == "failed" || pipeline.started_passing)'
    slack:
      channels:
        - "#search-et-alerts"
      message: "${BUILDKITE_MESSAGE}"

steps:
  - label: "🔨 Run e2e test"
    key: "e2e_test"
    agents:
      provider: aws
      instanceType: t3.medium
      imagePrefix: core-amazonlinux-2023
    command: ".buildkite/run_test.sh"

  - label: "🔨 Run FIPS e2e test"
    key: "fips_e2e_test"
    agents:
      provider: aws
      instanceType: t3.medium
      imagePrefix: core-amazonlinux-2023
    command: ".buildkite/run_fips_test.sh"

  - label: ":whale: Build and publish docker image"
    if: 'build.branch =~ /^((main)|([0-9]+\.[0-9]+))\$/'
    depends_on:
      - "e2e_test"
      - "fips_e2e_test"
    agents:
      image: "docker.elastic.co/ci-agent-images/drivah:0.30.0@sha256:68ac7589ee8817b8c3103191a5453de86c9922f5697100cd7e2d18df2586398c"
    command: "scripts/build-and-publish-docker-image.sh --push"
