---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

agents:
  image: "docker.elastic.co/ci-agent-images/drivah:0.18.1"

notify:
  - if: 'build.branch =~ /^((main)|([0-9]+\.[0-9]+))\$/ && (build.state == "failed" || pipeline.started_passing)'
    slack:
      channels:
        - "#search-et-alerts"
      message: "${BUILDKITE_MESSAGE}"

steps:
  - label: ":github: update version and tag"
    command: "scripts/release/update-release-version.sh"
  - wait
  - label: ":whale: Build docker image"
    command: "scripts/build-and-publish-docker-image.sh"
  - wait
  - label: ":github: create new maintenance branch"
    command: "scripts/release/create-new-branch.sh"
